# JFrog Frogbot Config file supports multiple repository configuration.
# It is important to note that 'scan-pull-request' and 'create-fix-pull-request' only work on a single repository, thus only the first repository in the configuration file will be used.
# Please use 'scan-pull-requests' command to apply the multiple repository configurations.

- repoName: "npm_example_project" # Repository name
  includeAllVulnerabilities: true # Displays all existing vulnerabilities, including the ones that were added by the pull request. [Default: false]
  failOnSecurityIssues: false # Fails the Frogbot task if any security issue is found. [Default: false]
  projects: # List of package manager related projects (e.g. npm, pip, maven projects) with their relevant working directories, installation command, etc.
    - installCommandName: "npm" # Installation command (e.g. npm, maven). Manda
      installCommandArgs: # List of arguments to the installation command (e.g. install, i)
        - "i"
- repoName: "go_example_project" # Repository name
  includeAllVulnerabilities: true # Displays all existing vulnerabilities, including the ones that were added by the pull request. [Default: false]