name: "Frogbot Scan and Fix Repositories"
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  scan-pull-requests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install prerequisites

      - uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      
      # Uncomment if you have a Pip/Pipenv/Poetry project
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.x"

      # Uncomment if you have Pipenv project
      # - name: Install poetry
      #   run: pip3 install poetry

      # Uncomment if you have Poetry project
      # - name: Setup Poetry
      #   run: pip3 install poetry

      # Uncomment if you have NuGet project
      # - uses: nuget/setup-nuget@v1
      #   with:
      #     nuget-version: "5.x"

      # Uncomment if you have .NET project
      # - uses: actions/setup-dotnet@v2
      #   with:
      #     dotnet-version: "3.1.x"

      # Uncomment if you have Maven/Gradle project
      # - name: Set up Java
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: "11"
      #     distribution: "temurin"

      # Uncomment if you have Gradle project
      # - name: Setup Gradle
      #   uses: gradle/gradle-build-action@v2

      - run: ./frogbot scan-and-fix-repos
        env:
          # [Mandatory]
          # JFrog platform URL (This functionality requires version 3.29.0 or above of Xray)
          JF_URL: ${{ secrets.JF_URL }}

          # [Mandatory if JF_ACCESS_TOKEN is not provided]
          # JFrog username with 'read' permissions for Xray. Must be provided with JF_PASSWORD
          # JF_USER: ${{ secrets.JF_USER }}

          # [Mandatory if JF_ACCESS_TOKEN is not provided]
          # JFrog password. Must be provided with JF_USER
          # JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

          # [Mandatory]
          # GitHub Personal Access Token (PAT)
          JF_GIT_TOKEN: ${{ secrets.GH_PAT }}

          # [Mandatory if JF_USER and JF_PASSWORD are not provided]
          # JFrog access token with 'read' permissions on Xray service
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          # [Optional, default: https://api.github.com]
          # API endpoint to GitHub
          # JF_GIT_API_ENDPOINT: https://github.example.com

          # Predefined - no need to set the following environment variables.
          JF_GIT_PROVIDER: 'github'
          JF_GIT_OWNER: ${{ github.repository_owner }}
